### ISSUE TITLE
Can't run the cheat

### ISSUE THREAD

**Issue by XPRSSN** [ALittlePatate/Rainbow-v2#1]
I installed requirements, tried to run the cheat and got this error:
Dumping the netvars, hold a sec...
2021-03-06 14:52:08,362 - pymem - DEBUG - Process 9196 is being debugged
Netvars dumped !
[INFO   ] [Logger      ] Record log in C:\Users\dalak\.kivy\logs\kivy_21-03-06_5.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\Users\dalak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\dalak\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pil (img_sdl2, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pil(['text_sdl2'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - ImportError: DLL load failed while importing _window_sdl2: The specified module could not be found.
  File "C:\Users\dalak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kivy\core\__init__.py", line 58, in core_select_lib
    mod = __import__(name='{2}.{0}.{1}'.format(
  File "C:\Users\dalak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kivy\core\window\window_sdl2.py", line 27, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

[CRITICAL] [App         ] Unable to get a Window, abort.
2021-03-06 14:52:13,883 - pymem - DEBUG - Process 9196 is being debugged
2021-03-06 14:52:13,884 - pymem - DEBUG - Process 9196 is being debugged

Is there any way to fix this and run the cheat?

**Comment by zlataovce** [comment]
don't use the microsoft store python, it sucks

**Comment by XPRSSN** [comment]
ok. I installed python 3.8, installed, tried installing the requirements (got an error on importlib), tried running the cheat and got this:
Traceback (most recent call last):
  File "C:\Users\dalak\Desktop\Rainbow-v2-main\Rainbow.py", line 5, in <module>
    from features_check import check
ModuleNotFoundError: No module named 'features_check'
What can I do to fix this?

**Comment by ALittlePatate** [comment]
> ok. I installed python 3.8, installed, tried installing the requirements (got an error on importlib), tried running the cheat and got this:
> Traceback (most recent call last):
> File "C:\Users\dalak\Desktop\Rainbow-v2-main\Rainbow.py", line 5, in
> from features_check import check
> ModuleNotFoundError: No module named 'features_check'
> What can I do to fix this?

That's kinda weird actually, i worked for me on Python 3.6.8.

`C:\Program Files\Python36\Scripts>pip.exe install importlib
Collecting importlib
  Using cached importlib-1.0.4-py3-none-any.whl
Installing collected packages: importlib
Successfully installed importlib-1.0.4`

**Comment by zlataovce** [comment]
importlib doesn't work for me either, python 3.8

**Comment by ALittlePatate** [comment]
Maybe try to use Python 3.6.8, maybe that's the problem ? I"m very confused haha
