### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by Sheijian** [ALittlePatate/Rainbow-v2#3]
yesterday it worked fine but today it just spams "Could not read memory at: 264, length: 4 - GetLastError: 299" in the console and nothing is working. I didnt change anything since yesterday :/

**Comment by FloGo3308** [comment]
Good chance that the offsets chaged, I think it will update automaticly when it gets the new offsets(takes at most 2 days, but most of the time it will be within hours)

**Comment by ALittlePatate** [comment]
Yeah it's the problem, all the netvars are dumper automatically by the cheat so they are not a problem. But i get the signatures from https://github.com/frk1/hazedumper and they sometimes take a bit of time to update them. Just wait :)
