### ISSUE TITLE
[Question] PyInstaller + security

### ISSUE THREAD

**Issue by skhrlx** [ALittlePatate/Rainbow-v2#4]
Since is a python script, i believe it's more secure to run it normally using the .py file, but, I made my own cheat, 100% writed by me, line per line, 100% private, using the PyInstaller, it can decrease the security of the cheat? (Probably, but I will build an .exe, for portability reasons, if I travel or any thing....)
"Since ratpoison, esencially is a script too", and, they recomend build it and, and it only got detected after years....
Please, don't be rude, I knew what this question is questionable, but, I want to know what you think

**Comment by ALittlePatate** [comment]
Well that's a great question actually. From what i know and experienced, using the .exe shouldn't be less secure. But i didn't do further investigations in using the exe because i was working with a non compilable version. So i don't really have an answer for you, but it should be secure anyways
