### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by ZelKed** [ALittlePatate/Rainbow-v2#9]
![image](https://user-images.githubusercontent.com/76404202/174441806-ab8f28a5-fc46-4577-baa8-3a9c9e9eb0cf.png)

(Btw i dont hack in publics only vs bots :)

**Comment by ZelKed** [comment]
wait 1 sec

**Comment by ZelKed** [comment]
got more errors

**Comment by ALittlePatate** [comment]
Well this cheat is no longer maintained and contains a lot of bad code, i can't help you on this as it was working for my python version (3.6.8 if im correct)
